// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyjacqpuwzmmwmspauot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5amFjcXB1d3ptbXdtc3BhdW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjExMTksImV4cCI6MjA2NjgzNzExOX0.y8Acf-mCkdGt5EHGAuiHKN2YtpXR3NUeGEkimD0o-KQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});